# Generated by Django 4.1.6 on 2023-02-07 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Country')),
                ('alpha2Code', models.CharField(blank=True, max_length=3, null=True, verbose_name='Country alpha2 Code')),
                ('alpha3Code', models.CharField(blank=True, max_length=3, null=True, verbose_name='Country alpha3 Code')),
                ('flag', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Country Code')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Deleted')], default=1)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='State')),
                ('initial', models.CharField(max_length=256, verbose_name='Initial')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Deleted')], default=1)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_states', to='addresses.country')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='City')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Deleted')], default=1)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_cities', to='addresses.state')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=512, verbose_name='Address')),
                ('number', models.CharField(blank=True, max_length=128, null=True, verbose_name='Number')),
                ('complement', models.CharField(blank=True, max_length=128, null=True, verbose_name='Complement')),
                ('neighborhood', models.CharField(blank=True, max_length=128, null=True, verbose_name='Neighborhood')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_city', to='addresses.city')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'addresses',
            },
        ),
    ]
