# Generated by Django 4.0.6 on 2022-07-22 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='State')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_states', to='countries.country')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='City')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_cities', to='addresses.state')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=512, verbose_name='Address')),
                ('number', models.CharField(blank=True, max_length=128, null=True, verbose_name='Number')),
                ('complement', models.CharField(blank=True, max_length=128, null=True, verbose_name='Complement')),
                ('neighborhood', models.CharField(blank=True, max_length=128, null=True, verbose_name='Neighborhood')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_city', to='addresses.city')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'addresses',
            },
        ),
    ]
