# Generated by Django 4.1.6 on 2023-02-07 21:29

import accounts.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nick_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Nickname')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Changed')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Pre_registered'), (3, 'Deleted')], default=1, verbose_name='Status')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is_staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='is_superuser')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_avatar', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.CharField(max_length=1024, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'User Avatar',
                'verbose_name_plural': 'Users Avatars',
                'db_table': 'users_avatars',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_data', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.IntegerField(choices=[(1, 'Teacher'), (2, 'Student'), (3, 'Admin_Master')], default=2, verbose_name='User Type')),
                ('age', models.IntegerField(null=True, verbose_name='User Age')),
                ('phone', models.CharField(max_length=126, null=True, verbose_name='Phone')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], null=True, verbose_name='User Gender')),
                ('birthday', models.DateField(null=True, verbose_name='Born Date')),
                ('document', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Document')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='addresses.address')),
                ('born_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_born_country', to='addresses.country')),
                ('born_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_born_language', to='languages.countrylanguage')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_city', to='addresses.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_country', to='addresses.country')),
                ('interest_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_interested_language', to='languages.language')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_state', to='addresses.state')),
            ],
            options={
                'verbose_name': 'Dados do usuário',
                'verbose_name_plural': 'Dados dos usuários',
                'db_table': 'user_data',
            },
        ),
    ]
