# Generated by Django 4.1.6 on 2023-02-07 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('languages', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='addresses',
        ),
        migrations.AddField(
            model_name='userdata',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='addresses.address'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='born_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_born_language', to='languages.countrylanguage'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='interest_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_interested_language', to='languages.countrylanguage'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_city', to='addresses.city'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_state', to='addresses.state'),
        ),
    ]
