# Generated by Django 4.0.6 on 2022-07-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agegroup',
            name='description',
            field=models.CharField(default='', max_length=120, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Deleted')], default=1, verbose_name='Status'),
        ),
    ]
